apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: francesco-belacca-site
    newName: ghcr.io/macel94/francesco-belacca-site
    newTag: sha-7194d65434ad4ef55e92ae145789574beae5c32a
