apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: francesco-belacca-site
    newName: ghcr.io/macel94/francesco-belacca-site
    newTag: sha-c22bd17e6dea15e0fb25e12068d23b42931d200f
