apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: portfolio

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

images:
  - name: francesco-belacca-site
    newName: ghcr.io/macel94/francesco-belacca-site
    newTag: sha-542ca592f48035a736aa16cc83f8b7ac6ed2da04
